## PROYECTO INDIVIDUAL SOYHENRY Nº2

In [1]:
#Librerias a usar

import numpy as np
import pandas as pd

In [2]:
#Abrir archivo homicidios.xlsx y creamos 2 dataframes con las hojas "HECHOS" y "VICTIMAS"

df_hechos = pd.read_excel('homicidios.xlsx', sheet_name='HECHOS')
df_vic = pd.read_excel('homicidios.xlsx', sheet_name='VICTIMAS')

In [3]:
df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [4]:
df_vic

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50,2021-12-12 00:00:00
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00

In [5]:
#Verificar si hay datos nulos en df1
df_hechos.isnull().sum()

ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       0
HH                         0
LUGAR_DEL_HECHO            0
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    0
ACUSADO                    0
dtype: int64

In [6]:
#Verificar si hay datos nulos en df2
df_vic.isnull().sum()

ID_hecho               0
FECHA                  0
AAAA                   0
MM                     0
DD                     0
ROL                    0
VICTIMA                0
SEXO                   0
EDAD                   0
FECHA_FALLECIMIENTO    0
dtype: int64

In [7]:
#Reemplazamos los "SD" por NaN

df_hechos = df_hechos.replace('SD', np.nan)
df_vic = df_vic.replace('SD', np.nan)

In [8]:
#Verificamos nuevamente datos nulos en df1
df_hechos.isnull().sum()

ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       1
HH                         1
LUGAR_DEL_HECHO            1
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    9
ACUSADO                   23
dtype: int64

In [9]:
#Verificamos nuevamente datos nulos en df2
df_vic.isnull().sum()

ID_hecho                0
FECHA                   0
AAAA                    0
MM                      0
DD                      0
ROL                    11
VICTIMA                 9
SEXO                    6
EDAD                   53
FECHA_FALLECIMIENTO    68
dtype: int64

In [10]:
df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4.0,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1.0,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7.0,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0.0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,NaN
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5.0,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17.0,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1.0,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0.0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10.0,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6.0,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [11]:
df_vic

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19.0,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70.0,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30.0,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18.0,NaN
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29.0,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50.0,2021-12-12 00:00:00
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18.0,2021-12-18 00:00:00
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43.0,2021-12-20 00:00:00
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27.0,2022-01-02 00:00:00
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60.0,2021-12-20 00:00:00

### ETL DF_hechos

In [12]:
#Lectura del dataframre

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4.0,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1.0,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7.0,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0.0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,NaN
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5.0,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17.0,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1.0,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0.0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10.0,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6.0,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [13]:
#Tipos de datos de las columnas

df_hechos.dtypes

ID                               object
N_VICTIMAS                        int64
FECHA                    datetime64[ns]
AAAA                              int64
MM                                int64
DD                                int64
HORA                             object
HH                              float64
LUGAR_DEL_HECHO                  object
TIPO_DE_CALLE                    object
Calle                            object
Altura                          float64
Cruce                            object
Dirección Normalizada            object
COMUNA                            int64
XY (CABA)                        object
pos x                            object
pos y                            object
PARTICIPANTES                    object
VICTIMA                          object
ACUSADO                          object
dtype: object

In [14]:
#Borramos la columna XY (CABA)

df_hechos = df_hechos.drop(['XY (CABA)'], axis=1)

In [15]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,Calle,Altura,Cruce,Dirección Normalizada,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4.0,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,PIEDRA BUENA AV.,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1.0,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,"PAZ, GRAL. AV.",NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7.0,AV ENTRE RIOS 2034,AVENIDA,ENTRE RIOS AV.,2034.0,NaN,ENTRE RIOS AV. 2034,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0.0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,LARRAZABAL AV.,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,-58.46503904,-34.68092974,MOTO-SD,MOTO,NaN
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5.0,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,SAN JUAN AV.,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17.0,AV. RIESTRA Y MOM,AVENIDA,RIESTRA AV.,NaN,MOM,RIESTRA AV. y MOM,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1.0,AU DELLEPIANE Y LACARRA,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL.",NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0.0,AV. GAONA Y TERRADA,AVENIDA,GAONA AV.,NaN,TERRADA,GAONA AV. y TERRADA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10.0,AV. EVA PERON 4071,AVENIDA,"PERON, EVA AV.",4071.0,NaN,"PERON, EVA AV. 4071",9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6.0,PADRE CARLOS MUJICA 709,CALLE,PADRE CARLOS MUJICA,709.0,NaN,PADRE CARLOS MUGICA 709,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [16]:
#Borramos las columnas LUGAR_DEL_HECHO , Altura , Cruce Y Dirección Normalizada

df_hechos = df_hechos.drop(['LUGAR_DEL_HECHO', 'Altura', 'Cruce', 'Dirección Normalizada'], axis=1)

In [17]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,Calle,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4.0,AVENIDA,PIEDRA BUENA AV.,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1.0,GRAL PAZ,"PAZ, GRAL. AV.",9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7.0,AVENIDA,ENTRE RIOS AV.,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0.0,AVENIDA,LARRAZABAL AV.,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,NaN
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5.0,AVENIDA,SAN JUAN AV.,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17.0,AVENIDA,RIESTRA AV.,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1.0,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL.",9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0.0,AVENIDA,GAONA AV.,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10.0,AVENIDA,"PERON, EVA AV.",9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6.0,CALLE,PADRE CARLOS MUJICA,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [18]:
#Cambiamos los NaN por 0 en la columna HH y Hora

df_hechos['HH'] = df_hechos['HH'].fillna(0)
df_hechos['Hora'] = df_hechos['HORA'].fillna(0)

In [19]:
#Cambiamos el tipo de datos de la columna HH a int

df_hechos['HH'] = df_hechos['HH'].astype(int)

In [20]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,Calle,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,Hora
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,PIEDRA BUENA AV.,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,GRAL PAZ,"PAZ, GRAL. AV.",9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,ENTRE RIOS AV.,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,LARRAZABAL AV.,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,NaN,00:00:00
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,SAN JUAN AV.,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,RIESTRA AV.,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL.",9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,GAONA AV.,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,"PERON, EVA AV.",9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,PADRE CARLOS MUJICA,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00

In [21]:
#Sustituimos los NaN de la columna acusado por "SD"

df_hechos['ACUSADO'] = df_hechos['ACUSADO'].fillna('SD')

In [22]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,Calle,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,Hora
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,PIEDRA BUENA AV.,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,GRAL PAZ,"PAZ, GRAL. AV.",9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,ENTRE RIOS AV.,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,LARRAZABAL AV.,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,00:00:00
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,SAN JUAN AV.,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,RIESTRA AV.,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL.",9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,GAONA AV.,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,"PERON, EVA AV.",9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,PADRE CARLOS MUJICA,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00

In [23]:
#Vemos los valores unicos de TIPO_DE_CALLE

df_hechos['TIPO_DE_CALLE'].unique()

array(['AVENIDA', 'GRAL PAZ', 'CALLE', 'AUTOPISTA'], dtype=object)

In [24]:
#Sustituimos "GRAL PAZ" por "AVENIDA"

df_hechos['TIPO_DE_CALLE'] = df_hechos['TIPO_DE_CALLE'].replace('GRAL PAZ', 'AVENIDA')

In [25]:
#Verificamos los valores unicos de TIPO_DE_CALLE

df_hechos['TIPO_DE_CALLE'].unique()

array(['AVENIDA', 'CALLE', 'AUTOPISTA'], dtype=object)

In [26]:
#Borramos la columna CALLE

df_hechos = df_hechos.drop(['Calle'], axis=1)

In [27]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,Hora
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,00:00:00
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00

In [28]:
#Vemos los tipos de datos

df_hechos.dtypes

ID                       object
N_VICTIMAS                int64
FECHA            datetime64[ns]
AAAA                      int64
MM                        int64
DD                        int64
HORA                     object
HH                        int32
TIPO_DE_CALLE            object
COMUNA                    int64
pos x                    object
pos y                    object
PARTICIPANTES            object
VICTIMA                  object
ACUSADO                  object
Hora                     object
dtype: object

In [29]:
#Vemos los valores unicos de la columna MM

df_hechos['MM'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [30]:
#Vemos los valores unicos de la columna AAAA

df_hechos['AAAA'].unique()

array([2016, 2017, 2018, 2019, 2020, 2021], dtype=int64)

In [31]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,Hora
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,00:00:00
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00

In [32]:
#Borramos las filas con datos nulos en las columnas HORA y VICTIMA

df_hechos = df_hechos.dropna(subset=['HORA', 'VICTIMA'])

In [33]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,Hora
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,00:00:00
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00

In [34]:
#Vemos cantidad de datos nulos en el df

df_hechos.isnull().sum()

ID               0
N_VICTIMAS       0
FECHA            0
AAAA             0
MM               0
DD               0
HORA             0
HH               0
TIPO_DE_CALLE    0
COMUNA           0
pos x            0
pos y            0
PARTICIPANTES    0
VICTIMA          0
ACUSADO          0
Hora             0
dtype: int64

In [50]:
#Reseteamos el indice

df_hechos = df_hechos.reset_index(drop=True)

In [51]:
#Lectura del dataframe

df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,Hora
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,00:00:00
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00
682,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00
683,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00
684,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00
685,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00

### ETL df_vic

In [35]:
#Lectura del dataframe

df_vic

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19.0,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70.0,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30.0,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18.0,NaN
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29.0,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50.0,2021-12-12 00:00:00
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18.0,2021-12-18 00:00:00
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43.0,2021-12-20 00:00:00
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27.0,2022-01-02 00:00:00
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60.0,2021-12-20 00:00:00

In [36]:
#Verificamos datos nulos o vacios en la columna FECHA

df_vic['FECHA'].isnull().sum()

0

In [37]:
#Borramos la columna FECHA_FALLECIMIENTO

df_vic = df_vic.drop(['FECHA_FALLECIMIENTO'], axis=1)

In [38]:
#Vemos valores unicos de la columna EDAD

df_vic['EDAD'].unique()

array([19., 70., 30., 18., 29., 22., 16., 59., 65., 34., 41., 50., 38.,
       21., 52., 36., 20., 54., nan, 56., 24., 78., 79., 26., 57., 37.,
       58., 23., 60., 42., 53., 51., 40., 87., 76., 75., 35., 80., 43.,
       45., 67., 27., 55., 49., 81., 25., 33., 46., 83., 39., 28.,  7.,
       48.,  4., 82., 32., 17., 47., 61., 10., 95., 73., 84., 66., 85.,
        1., 15., 13., 77., 44., 31., 62., 74., 71., 11., 86., 69., 72.,
       12., 63., 92., 68., 91., 64.,  5., 88.])

In [39]:
#Vemos valores nulos o vacios de la columna EDAD

df_vic['EDAD'].isnull().sum()

53

In [40]:
#Borramos las filas que tengan NaN en la columna EDAD

df_vic = df_vic.dropna(subset=['EDAD'])

In [41]:
#Lectura del dataframe 

df_vic

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19.0
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70.0
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30.0
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18.0
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29.0
...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50.0
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18.0
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43.0
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27.0
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60.0

In [42]:
#Cambiamos los tipos de datos de la columna EDAD a int

df_vic['EDAD'] = df_vic['EDAD'].astype(int)

In [43]:
#Lectura del dataframe

df_vic

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29
...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60

In [44]:
#Sustituimos los valores "PASAJERO_ACOMPAÑANTE" por "PASAJERO"

df_vic['ROL'] = df_vic['ROL'].replace('PASAJERO_ACOMPAÑANTE', 'PASAJERO')

In [45]:
#Lectura del dataframe

df_vic

      ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO  EDAD
0    2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO    19
1    2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO    70
2    2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO    30
3    2016-0004 2016-01-10  2016   1  10  CONDUCTOR    MOTO  MASCULINO    18
4    2016-0005 2016-01-21  2016   1  21  CONDUCTOR    MOTO  MASCULINO    29
..         ...        ...   ...  ..  ..        ...     ...        ...   ...
712  2021-0092 2021-12-12  2021  12  12     PEATON  PEATON   FEMENINO    50
713  2021-0093 2021-12-13  2021  12  13   PASAJERO    MOTO   FEMENINO    18
714  2021-0094 2021-12-20  2021  12  20   PASAJERO    MOTO   FEMENINO    43
715  2021-0095 2021-12-30  2021  12  30  CONDUCTOR    MOTO  MASCULINO    27
716  2021-0096 2021-12-15  2021  12  15  CONDUCTOR    AUTO  MASCULINO    60

[664 rows x 9 columns]

In [48]:
#Reseteamos el indice

df_vic = df_vic.reset_index(drop=True)

In [49]:
#Lectura del dataframe

df_vic

      ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO  EDAD
0    2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO    19
1    2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO    70
2    2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO    30
3    2016-0004 2016-01-10  2016   1  10  CONDUCTOR    MOTO  MASCULINO    18
4    2016-0005 2016-01-21  2016   1  21  CONDUCTOR    MOTO  MASCULINO    29
..         ...        ...   ...  ..  ..        ...     ...        ...   ...
659  2021-0092 2021-12-12  2021  12  12     PEATON  PEATON   FEMENINO    50
660  2021-0093 2021-12-13  2021  12  13   PASAJERO    MOTO   FEMENINO    18
661  2021-0094 2021-12-20  2021  12  20   PASAJERO    MOTO   FEMENINO    43
662  2021-0095 2021-12-30  2021  12  30  CONDUCTOR    MOTO  MASCULINO    27
663  2021-0096 2021-12-15  2021  12  15  CONDUCTOR    AUTO  MASCULINO    60

[664 rows x 9 columns]

### MERGED_DF

In [55]:
# Realiza un merge de ambos DataFrames 
merged_df = pd.merge(df_hechos, df_vic, left_on='ID', right_on='ID_hecho')

In [57]:
merged_df.isnull().sum()

ID                6
N_VICTIMAS        6
FECHA_x           6
AAAA_x            6
MM_x              6
DD_x              6
HORA              6
HH                6
TIPO_DE_CALLE     6
COMUNA            6
pos x             6
pos y             6
PARTICIPANTES     6
VICTIMA_x         6
ACUSADO           6
Hora              6
ID_hecho         44
FECHA_y          44
AAAA_y           44
MM_y             44
DD_y             44
ROL              50
VICTIMA_y        49
SEXO             44
EDAD             44
dtype: int64

In [59]:
merged_df.reset_index(drop=True)

,ID,N_VICTIMAS,FECHA_x,AAAA_x,MM_x,DD_x,HORA,HH,TIPO_DE_CALLE,COMUNA,...,Hora,ID_hecho,FECHA_y,AAAA_y,MM_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD
0,2016-0001,1.0,2016-01-01,2016.0,1.0,1.0,04:00:00,4.0,AVENIDA,8.0,...,04:00:00,2016-0001,2016-01-01,2016.0,1.0,1.0,CONDUCTOR,MOTO,MASCULINO,19.0
1,2016-0002,1.0,2016-01-02,2016.0,1.0,2.0,01:15:00,1.0,AVENIDA,9.0,...,01:15:00,2016-0002,2016-01-02,2016.0,1.0,2.0,CONDUCTOR,AUTO,MASCULINO,70.0
2,2016-0003,1.0,2016-01-03,2016.0,1.0,3.0,07:00:00,7.0,AVENIDA,1.0,...,07:00:00,2016-0003,2016-01-03,2016.0,1.0,3.0,CONDUCTOR,MOTO,MASCULINO,30.0
3,2016-0004,1.0,2016-01-10,2016.0,1.0,10.0,00:00:00,0.0,AVENIDA,8.0,...,00:00:00,2016-0004,2016-01-10,2016.0,1.0,10.0,CONDUCTOR,MOTO,MASCULINO,18.0
4,2016-0005,1.0,2016-01-21,2016.0,1.0,21.0,05:20:00,5.0,AVENIDA,1.0,...,05:20:00,2016-0005,2016-01-21,2016.0,1.0,21.0,CONDUCTOR,MOTO,MASCULINO,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-0029,2017-03-07,2017.0,3.0,7.0,NaN,NaN,MASCULINO,34.0
704,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-0074,2017-06-04,2017.0,6.0,4.0,NaN,NaN,MASCULINO,70.0
705,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-0089,2017-07-13,2017.0,7.0,13.0,NaN,NaN,MASCULINO,23.0
706,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-0155,2017-12-12,2017.0,12.0,12.0,NaN,NaN,MASCULINO,77.0
707,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2019-0103,2019-12-18,2019.0,12.0,18.0,CONDUCTOR,MOTO,MASCULINO,24.0

In [63]:
#Borramos los NaN 

merged_df = merged_df.dropna()

In [64]:
merged_df

,ID,N_VICTIMAS,FECHA_x,AAAA_x,MM_x,DD_x,HORA,HH,TIPO_DE_CALLE,COMUNA,...,Hora,ID_hecho,FECHA_y,AAAA_y,MM_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD
0,2016-0001,1.0,2016-01-01,2016.0,1.0,1.0,04:00:00,4.0,AVENIDA,8.0,...,04:00:00,2016-0001,2016-01-01,2016.0,1.0,1.0,CONDUCTOR,MOTO,MASCULINO,19.0
1,2016-0002,1.0,2016-01-02,2016.0,1.0,2.0,01:15:00,1.0,AVENIDA,9.0,...,01:15:00,2016-0002,2016-01-02,2016.0,1.0,2.0,CONDUCTOR,AUTO,MASCULINO,70.0
2,2016-0003,1.0,2016-01-03,2016.0,1.0,3.0,07:00:00,7.0,AVENIDA,1.0,...,07:00:00,2016-0003,2016-01-03,2016.0,1.0,3.0,CONDUCTOR,MOTO,MASCULINO,30.0
3,2016-0004,1.0,2016-01-10,2016.0,1.0,10.0,00:00:00,0.0,AVENIDA,8.0,...,00:00:00,2016-0004,2016-01-10,2016.0,1.0,10.0,CONDUCTOR,MOTO,MASCULINO,18.0
4,2016-0005,1.0,2016-01-21,2016.0,1.0,21.0,05:20:00,5.0,AVENIDA,1.0,...,05:20:00,2016-0005,2016-01-21,2016.0,1.0,21.0,CONDUCTOR,MOTO,MASCULINO,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2021-0093,1.0,2021-12-13,2021.0,12.0,13.0,17:10:00,17.0,AVENIDA,7.0,...,17:10:00,2021-0093,2021-12-13,2021.0,12.0,13.0,PASAJERO,MOTO,FEMENINO,18.0
698,2021-0094,1.0,2021-12-20,2021.0,12.0,20.0,01:10:00,1.0,AUTOPISTA,9.0,...,01:10:00,2021-0094,2021-12-20,2021.0,12.0,20.0,PASAJERO,MOTO,FEMENINO,43.0
699,2021-0095,1.0,2021-12-30,2021.0,12.0,30.0,00:43:00,0.0,AVENIDA,11.0,...,00:43:00,2021-0095,2021-12-30,2021.0,12.0,30.0,CONDUCTOR,MOTO,MASCULINO,27.0
700,2021-0096,1.0,2021-12-15,2021.0,12.0,15.0,10:30:00,10.0,AVENIDA,9.0,...,10:30:00,2021-0096,2021-12-15,2021.0,12.0,15.0,CONDUCTOR,AUTO,MASCULINO,60.0
701,2021-0097,1.0,2021-11-18,2021.0,11.0,18.0,06:10:00,6.0,CALLE,1.0,...,06:10:00,2021-0097,2021-11-18,2021.0,11.0,18.0,CICLISTA,BICICLETA,MASCULINO,53.0

In [65]:
#Borramos la columna ID_hecho

merged_df = merged_df.drop(['ID_hecho'], axis=1)

In [66]:
#Borramos las columnas AAAA_y y MM_y y DD_y

merged_df = merged_df.drop(['AAAA_y', 'MM_y', 'DD_y'], axis=1)

In [67]:
#Renombramos las columnas AAAA_x, MM_x y DD_x a AAAA, MM y DD

merged_df = merged_df.rename(columns={'AAAA_x': 'AAAA', 'MM_x': 'MM', 'DD_x': 'DD'})

In [74]:
#Convertimos a int las columnas AAAA, MM , DD , HH y COMUNA

merged_df['AAAA'] = merged_df['AAAA'].astype(int)
merged_df['MM'] = merged_df['MM'].astype(int)
merged_df['DD'] = merged_df['DD'].astype(int)
merged_df['HH'] = merged_df['HH'].astype(int)
merged_df['COMUNA'] = merged_df['COMUNA'].astype(int)

In [75]:
#Lectura del dataframe

merged_df

,ID,N_VICTIMAS,FECHA_x,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,...,pos y,PARTICIPANTES,VICTIMA_x,ACUSADO,Hora,FECHA_y,ROL,VICTIMA_y,SEXO,EDAD
0,2016-0001,1.0,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,...,-34.68757022,MOTO-AUTO,MOTO,AUTO,04:00:00,2016-01-01,CONDUCTOR,MOTO,MASCULINO,19.0
1,2016-0002,1.0,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,...,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,01:15:00,2016-01-02,CONDUCTOR,AUTO,MASCULINO,70.0
2,2016-0003,1.0,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,...,-34.63189362,MOTO-AUTO,MOTO,AUTO,07:00:00,2016-01-03,CONDUCTOR,MOTO,MASCULINO,30.0
3,2016-0004,1.0,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,...,-34.68092974,MOTO-SD,MOTO,SD,00:00:00,2016-01-10,CONDUCTOR,MOTO,MASCULINO,18.0
4,2016-0005,1.0,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,...,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,05:20:00,2016-01-21,CONDUCTOR,MOTO,MASCULINO,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2021-0093,1.0,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,...,-34.64561636,MOTO-AUTO,MOTO,AUTO,17:10:00,2021-12-13,PASAJERO,MOTO,FEMENINO,18.0
698,2021-0094,1.0,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,...,-34.65117757,MOTO-AUTO,MOTO,AUTO,01:10:00,2021-12-20,PASAJERO,MOTO,FEMENINO,43.0
699,2021-0095,1.0,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,...,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,00:43:00,2021-12-30,CONDUCTOR,MOTO,MASCULINO,27.0
700,2021-0096,1.0,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,...,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10:30:00,2021-12-15,CONDUCTOR,AUTO,MASCULINO,60.0
701,2021-0097,1.0,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,...,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,06:10:00,2021-11-18,CICLISTA,BICICLETA,MASCULINO,53.0

In [76]:
#Borramos la columna Hora

merged_df = merged_df.drop(['Hora'], axis=1)

In [77]:
#Lectura del dataframe

merged_df

,ID,N_VICTIMAS,FECHA_x,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA_x,ACUSADO,FECHA_y,ROL,VICTIMA_y,SEXO,EDAD
0,2016-0001,1.0,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,2016-01-01,CONDUCTOR,MOTO,MASCULINO,19.0
1,2016-0002,1.0,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,2016-01-02,CONDUCTOR,AUTO,MASCULINO,70.0
2,2016-0003,1.0,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,2016-01-03,CONDUCTOR,MOTO,MASCULINO,30.0
3,2016-0004,1.0,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,2016-01-10,CONDUCTOR,MOTO,MASCULINO,18.0
4,2016-0005,1.0,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,2016-01-21,CONDUCTOR,MOTO,MASCULINO,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2021-0093,1.0,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,2021-12-13,PASAJERO,MOTO,FEMENINO,18.0
698,2021-0094,1.0,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,2021-12-20,PASAJERO,MOTO,FEMENINO,43.0
699,2021-0095,1.0,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,2021-12-30,CONDUCTOR,MOTO,MASCULINO,27.0
700,2021-0096,1.0,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,2021-12-15,CONDUCTOR,AUTO,MASCULINO,60.0
701,2021-0097,1.0,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,2021-11-18,CICLISTA,BICICLETA,MASCULINO,53.0

In [78]:
#Borramos la columna FECHA_y

merged_df = merged_df.drop(['FECHA_y'], axis=1)

In [79]:
#Cambiamos los tipos de datos de la columna EDAD a int

merged_df['EDAD'] = merged_df['EDAD'].astype(int)

In [80]:
#Cambiamos los tipos de datos de la columna  N_VICTIMAS a int

merged_df['N_VICTIMAS'] = merged_df['N_VICTIMAS'].astype(int)

In [81]:
#Lectura del dataframe

merged_df

,ID,N_VICTIMAS,FECHA_x,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA_x,ACUSADO,ROL,VICTIMA_y,SEXO,EDAD
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MOTO,MASCULINO,19
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,AUTO,MASCULINO,70
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MOTO,MASCULINO,30
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,CONDUCTOR,MOTO,MASCULINO,18
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MOTO,MASCULINO,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,PASAJERO,MOTO,FEMENINO,18
698,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,PASAJERO,MOTO,FEMENINO,43
699,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MOTO,MASCULINO,27
700,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,CONDUCTOR,AUTO,MASCULINO,60
701,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,CICLISTA,BICICLETA,MASCULINO,53

In [82]:
#Borramos la columna ID

merged_df = merged_df.drop(['ID'], axis=1)

In [85]:
#Reseteamos el index nuevamente

merged_df = merged_df.reset_index(drop=True)

In [86]:
#Lectura del dataframe

merged_df

,N_VICTIMAS,FECHA_x,AAAA,MM,DD,HORA,HH,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,VICTIMA_x,ACUSADO,ROL,VICTIMA_y,SEXO,EDAD
0,1,2016-01-01,2016,1,1,04:00:00,4,AVENIDA,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MOTO,MASCULINO,19
1,1,2016-01-02,2016,1,2,01:15:00,1,AVENIDA,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,AUTO,MASCULINO,70
2,1,2016-01-03,2016,1,3,07:00:00,7,AVENIDA,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MOTO,MASCULINO,30
3,1,2016-01-10,2016,1,10,00:00:00,0,AVENIDA,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,CONDUCTOR,MOTO,MASCULINO,18
4,1,2016-01-21,2016,1,21,05:20:00,5,AVENIDA,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MOTO,MASCULINO,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
652,1,2021-12-13,2021,12,13,17:10:00,17,AVENIDA,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,PASAJERO,MOTO,FEMENINO,18
653,1,2021-12-20,2021,12,20,01:10:00,1,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,PASAJERO,MOTO,FEMENINO,43
654,1,2021-12-30,2021,12,30,00:43:00,0,AVENIDA,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MOTO,MASCULINO,27
655,1,2021-12-15,2021,12,15,10:30:00,10,AVENIDA,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,CONDUCTOR,AUTO,MASCULINO,60
656,1,2021-11-18,2021,11,18,06:10:00,6,CALLE,1,-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO,CICLISTA,BICICLETA,MASCULINO,53

In [87]:
#Guardamos el dataframe en un archivo csv

merged_df.to_csv('merged_df.csv', index=False)